// This is a simple program that returns a failure exit code.
fn main() {
    std::process::exit(1);
}
